// Generated by CoffeeScript 1.9.0
(function() {
  var EchoTask, Task, aliases, register;

  Task = require('task-registry');

  register = Task.register;

  aliases = Task.aliases;

  module.exports = EchoTask = (function() {
    function EchoTask() {}

    register(EchoTask);

    aliases(EchoTask, 'echo');

    EchoTask.prototype._executeSync = function(aFile) {
      return aFile;
    };

    return EchoTask;

  })();

}).call(this);
