// Generated by CoffeeScript 1.9.0
(function() {
  var Task, isdkTask;

  Task = require('task-registry');

  require('task-registry-template-engine-lodash');

  require('task-registry-file-template');

  require('task-registry-file-copy');

  require('task-registry-file-mkdir');

  require('task-registry-isdk');

  require('./tasks/echo');

  isdkTask = Task('isdk');

  isdkTask.executeSync({
    cwd: '.'
  });

}).call(this);
