// Generated by CoffeeScript 1.10.0
(function() {
  var Task, argv, isdkTask, loglevel, yargs;

  yargs = require('yargs');

  Task = require('task-registry');

  require('task-registry-template-engine-lodash');

  require('task-registry-file-template');

  require('task-registry-file-copy');

  require('task-registry-file-mkdir');

  require('task-registry-file-layout');

  require('task-registry-isdk');

  require('./tasks/echo');

  argv = yargs.count('verbose').alias('v', 'verbose').argv;

  isdkTask = Task('isdk');

  argv.cwd = argv._.length ? argv._[0] : '.';

  loglevel = argv.verbose;

  if (loglevel > 0) {
    argv.logger = {
      level: loglevel + 3
    };
  }

  isdkTask.executeSync(argv);

}).call(this);
